version: "3"
networks:
  default:
    external:
      name: traveler-dev
services:
  web:
    build: .
    volumes:
      - .:/app
      # exclude the node_modules
      - /app/node_modules
      - /app/docker
    ports:
      - "3001:3001"
      - "3443:3443"
    restart: unless-stopped
    command: nodemon app.js
    environment:
      - TRAVELER_CONFIG_REL_PATH=docker
